# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = 42_count.pdf

# List the files included in the slides
DEPS =

# Relative path to the LaTeX documentclass setup files
# Adapt as needed
RELPATH = ../latex/

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
